### ISSUE TITLE
To-Do List for the first major release

### ISSUE THREAD

**Issue by WatDuhHekBro** [WatDuhHekBro/Jukebox#1]
- [x] Modularize it so it can be released on its own.
- [x] Clickable speaker which toggles mute or not.
- [x] Custom fade times
- [x] Add an object that contains everything countdown-related. Also a sound manager.
- [x] Set the default timer to 3 minutes, 5 is way too long.
- [x] Pause timer when pausing song
- [x] Increase default fade to 5s
- [x] Support multiple shuffled playlists
- [x] Show how long a song has been playing for?
- [x] Show icon.png if no specific icon is found.

**Comment by WatDuhHekBro** [comment]
`Include default bg if bg.png isn't provided?` --> Solved by providing a generic look by default (light gray box) with a custom CSS file which overwrites the default settings.

**Comment by WatDuhHekBro** [comment]
- `Queue songs?` --> In a future version perhaps.
- `Make the icon fit if it's oversized for the current resolution.` --> Just make sure to optimize your icons to fit a small screen.

**Comment by WatDuhHekBro** [comment]
`Support selecting multiple songs in rapid succession (just intercept the timeouts to the new constructors).` --> In a future version.
